name: "Pull Request Labeler"

on:
  pull_request


jobs:
  formula-bump-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v3-preview
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.8.4
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
